# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

DOI_REGIONS = {
    "CGB": {
        "reg_num": 10,
        "reg_name": "California - Great Basin",
    },
    "CPN": {
        "reg_num": 9,
        "reg_name": "Columbia - Pacific Northwest",
    },
    "LCB": {
        "reg_num": 8,
        "reg_name": "Lower Colorado Basin",
    },
    "UCB": {
        "reg_num": 7,
        "reg_name": "Upper Colorado Basin",
    },
    "ART": {
        "reg_num": 6,
        "reg_name": "Arkansas - Rio Grande - Texas Gulf",
    },
    "MB": {
        "reg_num": 5,
        "reg_name": "Missouri Basin",
    },
}

LOCATION_IDS = {
    "AndersonRanch": 3249,
    "BighornLake": 275,
    "BlueMesa": 1533,
    "BoiseSystem": 3253,
    "BoysenDam": 281,
    "BuffaloBillDam": 269,
    "Calamus": 287,
    "CanyonFerry": 269,
    "CarterLakeDam": 288,
    "ChokeCanyon": 291,
    "ClarkCanyon": 294,
    "ElephantButteReservoir": 323,
    "FlamingGorge": 1535,
    "FolsomDam": 334,
    "FresnoDam": 337,
    "GibsonDam": 342,
    "GlendoDam": 345,
    "GranbyLake": 351,
    "GrandCoulee": 3272,
    "GreenMountainDam": 353,
    "GuernseyDam": 357,
    "HorsetoothDam": 369,
    "HungryHorseReservoir": 3278,
    "JamestownDam": 379,
    "KeyholeDam": 388,
    "KirwinDam": 391,
    "LakeElwell": 396,
    "LakeHavasu": 3515,
    "LakeMead": 3514,
    "LakeMohave": 3513,
    "LakePowell": 393,
    "LakeSherburne": 475,
    "LakeWaconda": 504,
    "McGeeCreek": 408,
    "McPheeDam": 410,
    "MillertonLake": 413,
    "NavajoDam": 423,
    "NewMelonesLake": 3204,
    "NortonDam": 390,
    "Palisades": 3292,
    "PathfinderDam": 433,
    "PuebloDam": 445,
    "SeminoeDam": 467,
    "ShadehillDam": 476,
    "ShastaLake": 471,
    "TrinityLake": 3203,
    "WhiskeytownLake": 509,
    # No matching sites below, using sequential IDs
    "AmericanFalls": 1,
    "CascadeLake": 2,
    "CleElum": 3,
    "DeschutesSystem": 4,
    "JacksonLake": 5,
    "LakeTschida": 6,
    "LuckyPeak": 7,
    "OwyheeDam": 8,
    "UpperKlamathLake": 9,
    "UpperSnakeSystem": 10,
    "YakimaSystem": 11,
}
