# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

# Mappings from resviz CSV to unified regions
DOI_REGIONS = {
    "California-Great Basin": {
        "reg_num": 10,
        "reg_name": "California - Great Basin",
    },
    "Columbia-Pacific Northwest": {
        "reg_num": 9,
        "reg_name": "Columbia - Pacific Northwest",
    },
    "Lower Colorado Basin": {
        "reg_num": 8,
        "reg_name": "Lower Colorado Basin",
    },
    "Upper Colorado Basin": {
        "reg_num": 7,
        "reg_name": "Upper Colorado Basin",
    },
    "Arkansas-Rio Grande-Texas Gulf": {
        "reg_num": 6,
        "reg_name": "Arkansas - Rio Grande - Texas Gulf",
    },
    "Missouri Basin": {
        "reg_num": 5,
        "reg_name": "Missouri Basin",
    },
}

# Mappings from resviz CSV to RISE stations
LOCATION_IDS = {
    "Agate": 7166,
    "Alcova": 259,
    "Altus": 3640,
    "American Falls": 7167,
    "Anchor": 262,
    "Anderson Ranch": 3249,
    "Angostura": 257,
    "Arrowrock": 3642,
    "Avalon": 267,
    "Banks Lake (Dry Falls Dam)": 7264,
    "Belle Fourche": 274,
    "Berryessa (Monticello Dam)": 272,
    "Beulah (Agency Valley Dam)": 3643,
    "Big Sandy": 277,
    "Bighorn (Yellowtail Dam)": 275,
    "Billy Clapp (Pinto Dam)": 7168,
    "Black Canyon (Black Canyon Diversion Dam)": 7175,
    "Blue Mesa": 1533,
    "Boysen": 281,
    "Box Butte": 268,
    "Brantley": 282,
    "Buffalo Bill": 269,
    "Bull Lake": 278,
    "Bully Creek": 3646,
    "Bumping Lake": 3647,
    "Caballo": 286,
    "Cachuma (Bradbury Dam)": 292,
    "Calamus (Virginia Smith Dam)": 287,
    "Cascade": 3645,
    "Canyon Ferry": 269,
    "Causey": 289,
    "Carter Lake": 288,
    "Choke Canyon": 291,
    "Clark Canyon": 294,
    "Clear Lake": 3702,
    "Clear Lake (Wasco Dam)": 7200,
    "Cle Elum": 7170,
    "Cold Springs": 7171,
    "Como": 3653,
    "Conconully Reservoir (Salmon Lake Dam)": 7169,
    "Crane Prairie": 7172,
    "Crawford": 3683,
    "Crescent Lake": 7173,
    "Crystal": 1534,
    "Currant Creek": 310,
    "Davis Creek": 311,
    "Deadwood": 3649,
    "Deer Creek": 314,
    "Deerfield": 315,
    "East Canyon": 319,
    "Echo": 320,
    "Eden (Eden Dikes)": 321,
    "Edward Arthur Patterson (Dickinson Dam)": 318,
    "El Vado": 324,
    "Elephant Butte": 323,
    "Elwell (Tiber Dam)": 396,
    "Emigrant": 7174,
    "Enders": 3656,
    "Estes (Olympus Dam)": 429,
    "Fish Lake": 7176,
    "Flaming Gorge": 1535,
    "Flatiron": 331,
    "Fontenelle": 1536,
    "Fort Cobb": 3657,
    "Foss": 3658,
    "Fourmile Lake": 7177,
    "Fruitgrowers": 338,
    "Folsom": 334,
    "Fresno": 337,
    "Gibson": 342,
    "Glendo": 345,
    "Granby": 351,
    "Grassy Lake": 7178,
    "Gray Reef": 3,
    "Green Mountain": 353,
    "Guernsey": 357,
    "Harry Strunk (Medicine Creek Dam)": 3650,
    "Havasu (Parker Dam)": 3515,
    "Haystack": 7179,
    "Helena Valley": 295,
    "Henry Hagg (Scoggins Dam)": 3651,
    "Heron": 365,
    "Horsetooth": 369,
    "Howard Prairie": 7182,
    "Hugh Butler (Red Willow Dam)": 3652,
    "Hungry Horse": 3278,
    "Hyatt": 7183,
    "Hyrum": 372,
    "Island Park": 7184,
    "Jamestown": 379,
    "Jackson Lake": 7185,
    "Jackson Gulch": 378,
    "Jordanelle": 384,
    "Kachess": 7186,
    "Keechelus": 7187,
    "Keith Sebelius (Norton Dam)": 390,
    "Keswick": 387,
    "Keyhole": 388,
    "Kirwin": 391,
    "Kortes": 3281,
    "Lake Alice": 266,
    "Lemon": 395,
    "Lewiston": 397,
    "Little Lake Alice": 394,
    "Little Wood River": 7202,
    "Lost Creek": 400,
    "Lost Lake": 3209,
    "Lovewell": 404,
    "Lowell (Deer Flat Dam)": 7188,
    "Mann (Reservoir A Dam)": 7198,
    "Mann Creek": 3663,
    "Marys Lake (Marys Lake Dikes)": 1,
    "Mason": 7195,
    "McGee Creek": 408,
    "McKay": 3364,
    "McPhee": 410,
    "Mead (Hoover Dam)": 3154,
    "Meeks Cabin": 411,
    "Merritt": 418,
    "Millerton (Friant Dam)": 413,
    "Minatare": 399,
    "Mohave (Davis Dam)": 3513,
    "Moon Lake": 416,
    "Morrow Point": 417,
    "Mt. Elbert Forebay": 3288,
    "Nambe Falls": 3511,
    "Nasworthy": 421,
    "Natoma (Nimbus Dam)": 422,
    "Navajo": 423,
    "New Melones": 3204,
    "Nelson (Nelson Dikes)": 424,
    "Newton": 425,
    "Nighthorse (Ridges Basin Dam)": 392,
    "Ochoco": 3665,
    "Owyhee": 7112,
    "Pactola": 444,
    "Paonia": 431,
    "Palisades": 3292,
    "Pathfinder": 433,
    "Pilot Butte": 435,
    "Pineview": 437,
    "Pinewood (Rattlesnake Dam)": 438,
    "Pishkun (Pishkun Dikes)": 443,
    "Platoro": 3512,
    "Potholes (O'Sullivan Dam)": 7265,
    "Powell (Glen Canyon Dam)": 393,
    "Prineville (Arthur R. Bowman Dam)": 3666,
    "Pueblo": 445,
    "Red Fleet": 447,
    "Ridgway": 448,
    "Rimrock (Tieton Dam)": 7169,
    "Ririe": 7197,
    "Rockport (Wanship Dam)": 453,
    "Ruedi": 456,
    "Scofield": 466,
    "Scooteney (Scooteney Dikes)": 7266,
    "Seminoe": 467,
    "Shadehill": 476,
    "Shadow Mountain": 473,
    "Shasta": 471,
    "Sherburne (Lake Sherburne Dam)": 475,
    "Silver Jack": 477,
    "Soldiers Meadow": 7199,
    "Spring Creek (Spring Creek Debris Dam)": 6,
    "Starvation": 484,
    "Stateline": 485,
    "Steinaker": 486,
    "Strawberry (Soldier Creek Dam)": 488,
    "Sumner": 489,
    "Swanson (Trenton Dam)": 3667,
    "Taylor Park": 491,
    "Thief Valley": 3668,
    "Thunderbird (Norman Dam)": 3674,
    "Tom Steed (Mountain Park Dam)": 3670,
    "Trial (Trial Lake Dam)": 3208,
    "Trinity": 3203,
    "Tschida (Heart Butte Dam)": 402,
    "Turquoise (Sugar Loaf Dam)": 498,
    "Twin Lakes": 499,
    "Unity": 3671,
    "Upper Stillwater": 500,
    "Utah Lake": 3206,
    "Vallecito": 501,
    "Waconda (Glen Elder Dam)": 504,
    "Walcott (Minidoka Dam)": 7191,
    "Warm Springs": 3672,
    "Washington (Washington Lake Dam)": 3207,
    "Webster": 506,
    "Whiskeytown": 509,
    "Wickiup": 7201,
    "Willard Bay (Arthur V. Watkins Dam)": 512,
    "Willow Creek Reservoir (CO)": 515,
    "Willow Creek Reservoir (MT)": 508,
}


# Mappings from state abbreviations to Geoconnex state URIs
STATE_MAPPING = {
    "AL": "https://geoconnex.us/ref/state/01",
    "AK": "https://geoconnex.us/ref/state/02",
    "AZ": "https://geoconnex.us/ref/state/04",
    "AR": "https://geoconnex.us/ref/state/05",
    "CA": "https://geoconnex.us/ref/state/06",
    "CO": "https://geoconnex.us/ref/state/08",
    "CT": "https://geoconnex.us/ref/state/09",
    "DE": "https://geoconnex.us/ref/state/10",
    "DC": "https://geoconnex.us/ref/state/11",
    "FL": "https://geoconnex.us/ref/state/12",
    "GA": "https://geoconnex.us/ref/state/13",
    "HI": "https://geoconnex.us/ref/state/15",
    "ID": "https://geoconnex.us/ref/state/16",
    "IL": "https://geoconnex.us/ref/state/17",
    "IN": "https://geoconnex.us/ref/state/18",
    "IA": "https://geoconnex.us/ref/state/19",
    "KS": "https://geoconnex.us/ref/state/20",
    "KY": "https://geoconnex.us/ref/state/21",
    "LA": "https://geoconnex.us/ref/state/22",
    "ME": "https://geoconnex.us/ref/state/23",
    "MD": "https://geoconnex.us/ref/state/24",
    "MA": "https://geoconnex.us/ref/state/25",
    "MI": "https://geoconnex.us/ref/state/26",
    "MN": "https://geoconnex.us/ref/state/27",
    "MS": "https://geoconnex.us/ref/state/28",
    "MO": "https://geoconnex.us/ref/state/29",
    "MT": "https://geoconnex.us/ref/state/30",
    "NE": "https://geoconnex.us/ref/state/31",
    "NV": "https://geoconnex.us/ref/state/32",
    "NH": "https://geoconnex.us/ref/state/33",
    "NJ": "https://geoconnex.us/ref/state/34",
    "NM": "https://geoconnex.us/ref/state/35",
    "NY": "https://geoconnex.us/ref/state/36",
    "NC": "https://geoconnex.us/ref/state/37",
    "ND": "https://geoconnex.us/ref/state/38",
    "OH": "https://geoconnex.us/ref/state/39",
    "OK": "https://geoconnex.us/ref/state/40",
    "OR": "https://geoconnex.us/ref/state/41",
    "PA": "https://geoconnex.us/ref/state/42",
    "RI": "https://geoconnex.us/ref/state/44",
    "SC": "https://geoconnex.us/ref/state/45",
    "SD": "https://geoconnex.us/ref/state/46",
    "TN": "https://geoconnex.us/ref/state/47",
    "TX": "https://geoconnex.us/ref/state/48",
    "UT": "https://geoconnex.us/ref/state/49",
    "VT": "https://geoconnex.us/ref/state/50",
    "VA": "https://geoconnex.us/ref/state/51",
    "WA": "https://geoconnex.us/ref/state/53",
    "WV": "https://geoconnex.us/ref/state/54",
    "WI": "https://geoconnex.us/ref/state/55",
    "WY": "https://geoconnex.us/ref/state/56",
    "AS": "https://geoconnex.us/ref/state/60",
    "GU": "https://geoconnex.us/ref/state/66",
    "MP": "https://geoconnex.us/ref/state/69",
    "PR": "https://geoconnex.us/ref/state/72",
    "UM": "https://geoconnex.us/ref/state/74",
    "VI": "https://geoconnex.us/ref/state/78",
}

NAME_TO_ID_MAPPING = {
    "Abiquiu Reservoir (Abiquiu Dam)": "Abiquiu",
    "Agate Reservoir (Agate Dam)": "Agate",
    "Alcova Reservoir (Alcova Dam)": "Alcova",
    "Lake Alice (Lake Alice Dams)": "Alice",
    "Little Lake Alice (Little Lake Alice Dam)": "Alice2",
    "Lake Altus (Altus Dam)": "Altus",
    "American Falls Reservoir (American Falls Dam)": "AmericanFalls",
    "Anchor Reservoir (Anchor Dam)": "Anchor",
    "Anderson Ranch Reservoir (Anderson Ranch Dam)": "AndersonRanch",
    "Angostura Reservoir (Angostura Dam)": "Angostura",
    "Arrowrock Reservoir (Arrowrock Dam)": "Arrowrock",
    "Avalon Reservoir (Avalon Dam)": "Avalon",
    "Banks Lake (Dry Falls Dam)": "Banks",
    "Belle Fourche Reservoir (Belle Fourche Dam)": "BelleFourche",
    "Lake Berryessa (Monticello Dam)": "Berryessa",
    "Beulah Reservoir (Agency Valley Dam)": "Beulah",
    "Big Sandy Reservoir (Big Sandy Dam)": "BigSandy",
    "Bighorn Lake (Yellowtail Dam)": "Bighorn",
    "Billy Clapp Lake (Pinto Dam)": "BillyClapp",
    "Black Canyon Reservoir (Black Canyon Diversion Dam)": "BlackCanyon",
    "Blue Mesa Reservoir (Blue Mesa Dam)": "BlueMesa",
    "Boca Reservoir (Boca Dam)": "Boca",
    "Box Butte Reservoir (Box Butte Dam)": "BoxButte",
    "Boysen Reservoir (Boysen Dam)": "Boysen",
    "Brantley Reservoir (Brantley Dam)": "Brantley",
    "Buffalo Bill Reservoir (Buffalo Bill Dam)": "BuffaloBill",
    "Bull Lake (Bull Lake Dam)": "Bull",
    "Bully Creek Reservoir (Bully Creek Dam)": "BullyCreek",
    "Bumping Lake (Bumping Lake Dam)": "Bumping",
    "Caballo Reservoir (Caballo Dam)": "Caballo",
    "Lake Cachuma (Bradbury Dam)": "Cachuma",
    "Calamus Reservoir (Virginia Smith Dam)": "Calamus",
    "Canyon Ferry Lake (Canyon Ferry Dam)": "CanyonFerry",
    "Carter Lake Reservoir (Carter Lake Dams)": "CarterLake",
    "Lake Cascade (Cascade Dam)": "Cascade",
    "Causey Reservoir (Causey Dam)": "Causey",
    "Cedar Bluff Reservoir (Cedar Bluff Dam)": "CedarBluff",
    "Cheney Reservoir (Cheney Dam)": "Cheney",
    "Choke Canyon Reservoir (Choke Canyon Dam)": "ChokeCanyon",
    "Clark Canyon Reservoir (Clark Canyon Dam)": "ClarkCanyon",
    "Cle Elum Lake (Cle Elum Dam)": "CleElum",
    "Clear Lake Reservoir (Clear Lake Dam)": "ClearLake",
    "Clear Lake (OR) (Wasco Dam)": "ClearLake(OR)",
    "Cochiti Lake (Cochiti Dam)": "Cochiti",
    "Cold Springs Reservoir (Cold Springs Dam)": "ColdSprings",
    "Lake Como (Como Dam)": "Como",
    "Conconully Lake (Salmon Lake Dam)": "ConconullyLake",
    "Conconully Reservoir (Conconully Dam)": "ConconullyReservoir",
    "Crane Prairie Reservoir (Crane Prairie Dam)": "CranePrairie",
    "Crawford Reservoir (Crawford Dam)": "Crawford",
    "Crescent Lake (Crescent Lake Dam)": "Crescent",
    "Crystal Reservoir (Crystal Dam)": "Crystal",
    "Currant Creek Reservoir (Currant Creek Dam)": "CurrantCreek",
    "Davis Creek Reservoir (Davis Creek Dam)": "DavisCreek",
    "Deadwood Reservoir (Deadwood Dam)": "Deadwood",
    "Deer Creek Reservoir (Deer Creek Dam)": "DeerCreek",
    "Deerfield Lake (Deerfield Dam)": "Deerfield",
    "East Canyon Reservoir (East Canyon Dam)": "EastCanyon",
    "Echo Reservoir (Echo Dam)": "Echo",
    "Eden Reservoir (Eden Dikes)": "Eden",
    "Edward Arthur Patterson Lake (Dickinson Dam)": "EdwardArthurPatterson",
    "El Vado Reservoir (El Vado Dam)": "ElVado",
    "Elephant Butte Reservoir (Elephant Butte Dam)": "ElephantButte",
    "Lake Elwell (Tiber Dam)": "Elwell",
    "Emigrant Reservoir (Emigrant Dam)": "Emigrant",
    "Enders Reservoir (Enders Dam)": "Enders",
    "Lake Estes (Olympus Dam)": "Estes",
    "Fish Lake (Fish Lake Dam)": "Fish",
    "Flaming Gorge Reservoir (Flaming Gorge Dam)": "FlamingGorge",
    "Flatiron Reservoir (Flatiron Dam)": "Flatiron",
    "Folsom Lake (Folsom Dam)": "Folsom",
    "Fontenelle Reservoir (Fontenelle Dam)": "Fontenelle",
    "Fort Cobb Reservoir (Fort Cobb Dam)": "FortCobb",
    "Fort Peck Lake (Fort Peck Dam)": "FortPeck",
    "#NAME?": "FortPeck",
    "Foss Reservoir (Foss Dam)": "Foss",
    "Fourmile Lake (Fourmile Lake Dam)": "Fourmile",
    "Franklin D. Roosevelt Lake (Grand Coulee Dam)": "FranklinD.Roosevelt",
    "Fresno Reservoir (Fresno Dam)": "Fresno",
    "Fruitgrowers Reservoir (Fruitgrowers Dam)": "Fruitgrowers",
    "Gerber Reservoir (Gerber Dam)": "Gerber",
    "Gibson Reservoir (Gibson Dam)": "Gibson",
    "Glendo Reservoir (Glendo Dam)": "Glendo",
    "Lake Granby (Granby Dam)": "Granby",
    "Grassy Lake (Grassy Lake Dam)": "Grassy",
    "Gray Reef Reservoir (Gray Reef Dam)": "GrayReef",
    "Green Mountain Reservoir (Green Mountain Dam)": "GreenMountain",
    "Guernsey Reservoir (Guernsey Dam)": "Guernsey",
    "Harry Strunk Lake (Medicine Creek Dam)": "HarryStrunk",
    "Lake Havasu (Parker Dam)": "Havasu",
    "Haystack Reservoir (Haystack Dam)": "Haystack",
    "Helena Valley Reservoir (Helena Valley Dam)": "HelenaValley",
    "Henry Hagg Lake (Scoggins Dam)": "HenryHagg",
    "Heron Reservoir (Heron Dam)": "Heron",
    "Horsetooth Reservoir (Horsetooth Dam)": "Horsetooth",
    "Howard Prairie Reservoir (Howard Prairie Dam)": "HowardPrairie",
    "Hugh Butler Lake (Red Willow Dam)": "HughButler",
    "Hungry Horse Reservoir (Hungry Horse Dam)": "HungryHorse",
    "Hyatt Reservoir (Hyatt Dam)": "Hyatt",
    "Hyrum Reservoir (Hyrum Dam)": "Hyrum",
    "Island Park Reservoir (Island Park Dam)": "IslandPark",
    "Jackson Lake (Jackson Lake Dam)": "Jackson",
    "Jackson Gulch Reservoir (Jackson Gulch Dam)": "JacksonGulch",
    "Jamestown Reservoir (Jamestown Dam)": "Jamestown",
    "Jordanelle Reservoir (Jordanelle Dam)": "Jordanelle",
    "Kachess Lake (Kachess Dam)": "Kachess",
    "Keechelus Lake (Keechelus Dam)": "Keechelus",
    "Keith Sebelius Lake (Norton Dam)": "KeithSebelius",
    "Keswick Reservoir (Keswick Dam)": "Keswick",
    "Keyhole Reservoir (Keyhole Dam)": "Keyhole",
    "Kirwin Reservoir (Kirwin Dam)": "Kirwin",
    "Kortes Reservoir (Kortes Dam)": "Kortes",
    "Lahontan Reservoir (Lahontan Dam)": "Lahontan",
    "Lake Of The Arbuckles (Arbuckle Dam)": "LakeOfTheArbuckles",
    "Lemon Reservoir (Lemon Dam)": "Lemon",
    "Lewiston Lake (Lewiston Dam)": "Lewiston",
    "Little Wood River Reservoir (Little Wood River Dam)": "LittleWoodRiver",
    "Lost Lake (Lost Lake Dam)": "Lost",
    "Lost Creek Reservoir (Lost Creek Dam)": "LostCreek",
    "Lovewell Reservoir (Lovewell Dam)": "Lovewell",
    "Lake Lowell (Deer Flat Dam)": "Lowell",
    "Lucky Peak Reservoir (Lucky Peak Dam)": "LuckyPeak",
    "Mann Lake (Reservoir A Dam)": "Mann",
    "Mann Creek Reservoir (Mann Creek Dam)": "MannCreek",
    "Marys Lake (Marys Lake Dikes)": "Marys",
    "Mason Reservoir (Mason Dam)": "Mason",
    "McGee Creek Reservoir (McGee Creek Dam)": "McGeeCreek",
    "McKay Reservoir (McKay Dam)": "McKay",
    "McPhee Reservoir (McPhee Dam)": "McPhee",
    "Lake Mead (Hoover Dam)": "Mead",
    "Meeks Cabin Reservoir (Meeks Cabin Dam)": "MeeksCabin",
    "Lake Meredith (Sanford Dam)": "Meredith",
    "Merritt Reservoir (Merritt Dam)": "Merritt",
    "Millerton Lake (Friant Dam)": "Millerton",
    "Lake Minatare (Minatare Dam)": "Minatare",
    "Lake Mohave (Davis Dam)": "Mohave",
    "Moon Lake (Moon Lake Dam)": "Moon",
    "Morrow Point Reservoir (Morrow Point Dam)": "MorrowPoint",
    "Mt. Elbert Forebay (Mt. Elbert Forebay Dam)": "Mt.ElbertForebay",
    "Nambe Falls Reservoir (Nambe Falls Dam)": "NambeFalls",
    "Lake Nasworthy (Nasworthy Dam)": "Nasworthy",
    "Lake Natoma (Nimbus Dam)": "Natoma",
    "Navajo Reservoir (Navajo Dam)": "Navajo",
    "Nelson Reservoir (Nelson Dikes)": "Nelson",
    "New Melones Lake (New Melones Dam)": "NewMelones",
    "Newton Reservoir (Newton Dam)": "Newton",
    "Lake Nighthorse (Ridges Basin Dam)": "Nighthorse",
    "Ochoco Reservoir (Ochoco Dam)": "Ochoco",
    "Lake Owyhee (Owyhee Dam)": "Owyhee",
    "Pactola Reservoir (Pactola Dam)": "Pactola",
    "Palisades Reservoir (Palisades Dam)": "Palisades",
    "Paonia Reservoir (Paonia Dam)": "Paonia",
    "Pathfinder Reservoir (Pathfinder Dam)": "Pathfinder",
    "Pilot Butte Reservoir (Pilot Butte Dam)": "PilotButte",
    "Pineview Reservoir (Pineview Dam)": "Pineview",
    "Pinewood Lake (Rattlesnake Dam)": "Pinewood",
    "Pishkun Reservoir (Pishkun Dikes)": "Pishkun",
    "Platoro Reservoir (Platoro Dam)": "Platoro",
    "Potholes Reservoir (O'Sullivan Dam)": "Potholes",
    "Lake Powell (Glen Canyon Dam)": "Powell",
    "Prineville Reservoir (Arthur R. Bowman Dam)": "Prineville",
    "Prosser Creek Reservoir (Prosser Creek Dam)": "ProsserCreek",
    "Pueblo Reservoir (Pueblo Dam)": "Pueblo",
    "Red Fleet Reservoir (Red Fleet Dam)": "RedFleet",
    "Ridgway Reservoir (Ridgway Dam)": "Ridgway",
    "Rifle Gap Reservoir (Rifle Gap Dam)": "RifleGap",
    "Rimrock Lake (Tieton Dam)": "Rimrock",
    "Ririe Reservoir (Ririe Dam)": "Ririe",
    "Rockport Lake (Wanship Dam)": "Rockport",
    "Ruedi Reservoir (Ruedi Dam)": "Ruedi",
    "Santa Rosa Lake (Santa Rosa Dam)": "SantaRosa",
    "Scofield Reservoir (Scofield Dam)": "Scofield",
    "Scooteney Reservoir (Scooteney Dikes)": "Scooteney",
    "Seminoe Reservoir (Seminoe Dam)": "Seminoe",
    "Shadehill Reservoir (Shadehill Dam)": "Shadehill",
    "Shadow Mountain Lake (Shadow Mountain Dam)": "ShadowMountain",
    "Shasta Lake (Shasta Dam)": "Shasta",
    "Lake Sherburne (Lake Sherburne Dam)": "Sherburne",
    "Silver Jack Reservoir (Silver Jack Dam)": "SilverJack",
    "Soldiers Meadow Reservoir (Soldiers Meadow Dam)": "SoldiersMeadow",
    "Spring Creek Reservoir (Spring Creek Debris Dam)": "SpringCreek",
    "Stampede Reservoir (Stampede Dam)": "Stampede",
    "Starvation Reservoir (Starvation Dam)": "Starvation",
    "Stateline Reservoir (Stateline Dam)": "Stateline",
    "Steinaker Reservoir (Steinaker Dam)": "Steinaker",
    "Strawberry Reservoir (Soldier Creek Dam)": "Strawberry",
    "Sumner Lake (Sumner Dam)": "Sumner",
    "Swanson Lake (Trenton Dam)": "Swanson",
    "Lake Tahoe Reservoir (Lake Tahoe Dam)": "Tahoe",
    "Taylor Park Reservoir (Taylor Park Dam)": "TaylorPark",
    "Thief Valley Reservoir (Thief Valley Dam)": "ThiefValley",
    "Lake Thunderbird (Norman Dam)": "Thunderbird",
    "Tom Steed Reservoir (Mountain Park Dam)": "TomSteed",
    "Trial Lake (Trial Lake Dam)": "Trial",
    "Trinity Lake (Trinity Dam)": "Trinity",
    "Lake Tschida (Heart Butte Dam)": "Tschida",
    "Turquoise Lake (Sugar Loaf Dam)": "Turquoise",
    "Twin Buttes Reservoir (Twin Buttes Dam)": "TwinButtes",
    "Twin Lakes (Twin Lakes Dam)": "TwinLakes",
    "Unity Reservoir (Unity Dam)": "Unity",
    "Upper Klamath Lake (Link River Diversion Dam)": "UpperKlamath",
    "Upper Stillwater Reservoir (Upper Stillwater Dam)": "UpperStillwater",
    "Utah Lake": "Utah",
    "Vallecito Reservoir (Vallecito Dam)": "Vallecito",
    "Vega Reservoir (Vega Dam)": "Vega",
    "Waconda Lake (Glen Elder Dam)": "Waconda",
    "Lake Walcott (Minidoka Dam)": "Walcott",
    "Warm Springs Reservoir (Warm Springs Dam)": "WarmSprings",
    "Washington Lake (Washington Lake Dam)": "Washington",
    "Webster Reservoir (Webster Dam)": "Webster",
    "Whiskeytown Lake (Whiskeytown Dam)": "Whiskeytown",
    "Wickiup Reservoir (Wickiup Dam)": "Wickiup",
    "Willard Bay Reservoir (Arthur V. Watkins Dam)": "WillardBay",
    "Willow Creek Reservoir (CO) (Willow Creek Dam)": "WillowCreekReservoirCO",
    "Willow Creek Reservoir (MT) (Willow Creek Dam)": "WillowCreekReservoirMT",
}
