# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

[project]
name = "cpnr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geoalchemy2>=0.17.1",
    "pg-edr",
    "psycopg2>=2.9.10",
]

[tool.uv]
package = true

[tool.uv.sources]
pg-edr = { url = "https://github.com/internetofwater/pgedr/archive/refs/heads/main.zip" }

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project.scripts]
cpnr = "cpnr:load"

[tool.hatch.build.targets.wheel]
packages = ["cpnr"]

[tool.hatch.metadata]
allow-direct-references = true
