# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

# generated by datamodel-codegen:
#   filename:  https://cwms-data.usace.army.mil/cwms-data/swagger-docs
#   timestamp: 2025-04-03T18:29:45+00:00

from __future__ import annotations

from typing import Annotated, Optional

from msgspec import Meta, Struct, field


class Column(Struct):
    name: Optional[str] = None
    ordinal: Optional[int] = None
    datatype: Optional[str] = None


class Record(Struct):
    date_time: Optional[
        Annotated[
            int,
            Meta(description="Milliseconds since 1970-01-01 (Unix Epoch), always UTC"),
        ]
    ] = field(name="date-time", default=None)
    value: Optional[
        Annotated[float, Meta(description="Requested time-series data value")]
    ] = None
    quality_code: Optional[int] = field(name="quality-code", default=None)
