# generated by datamodel-codegen:
#   filename:  https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
#   timestamp: 2025-07-07T15:48:07+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Dict, List, Optional


@dataclass
class DataValueDTO:
    date: Optional[str] = None
    month: Optional[int] = None
    monthPart: Optional[str] = None
    year: Optional[int] = None
    collectionDate: Optional[str] = None
    value: Optional[float] = None
    qcFlag: Optional[str] = None
    qaFlag: Optional[str] = None
    origValue: Optional[float] = None
    origQcFlag: Optional[str] = None
    average: Optional[float] = None
    median: Optional[float] = None


@dataclass
class DcoDTO:
    code: Optional[str] = None
    name: Optional[str] = None


@dataclass
class DurationDTO:
    code: Optional[str] = None
    name: Optional[str] = None
    durationMinutes: Optional[str] = None


@dataclass
class ElementDTO:
    code: Optional[str] = None
    name: Optional[str] = None
    physicalElementName: Optional[str] = None
    functionCode: Optional[str] = None
    dataPrecision: Optional[int] = None
    description: Optional[str] = None
    storedUnitCode: Optional[str] = None
    englishUnitCode: Optional[str] = None
    metricUnitCode: Optional[str] = None


@dataclass
class ForecastDataDTO:
    elementCode: Optional[str] = None
    forecastPeriod: Optional[List[str]] = None
    forecastStatus: Optional[str] = None
    issueDate: Optional[str] = None
    periodNormal: Optional[float] = None
    publicationDate: Optional[str] = None
    unitCode: Optional[str] = None
    forecastValues: Optional[Dict[str, float]] = None


@dataclass
class ForecastPeriodDTO:
    code: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    beginMonthDay: Optional[str] = None
    endMonthDay: Optional[str] = None


@dataclass
class ForecastPointDTO:
    name: Optional[str] = None
    forecaster: Optional[str] = None
    exceedenceProbabilities: Optional[List[int]] = None


@dataclass
class FunctionDTO:
    code: Optional[str] = None
    abbreviation: Optional[str] = None
    name: Optional[str] = None


@dataclass
class InstrumentDTO:
    name: Optional[str] = None
    transducerLength: Optional[int] = None
    dataPrecisionAdjustment: Optional[int] = None
    manufacturer: Optional[str] = None
    model: Optional[str] = None
    active: Optional[bool] = None


@dataclass
class NetworkDTO:
    code: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None


@dataclass
class PhysicalElementDTO:
    name: Optional[str] = None
    shefPhysicalElementCode: Optional[str] = None


@dataclass
class ReservoirMetadataDTO:
    capacity: Optional[float] = None
    elevationAtCapacity: Optional[float] = None
    usableCapacity: Optional[float] = None


@dataclass
class StateDTO:
    code: Optional[str] = None
    fipsNumber: Optional[str] = None
    name: Optional[str] = None
    countryCode: Optional[str] = None


class DurationName(Enum):
    DAILY = "DAILY"
    HOURLY = "HOURLY"
    SEMIMONTHLY = "SEMIMONTHLY"
    MONTHLY = "MONTHLY"
    CALENDAR_YEAR = "CALENDAR_YEAR"
    WATER_YEAR = "WATER_YEAR"
    INSTANTANEOUS = "INSTANTANEOUS"
    SEASONAL = "SEASONAL"
    DAILY__HOURLY__SEMIMONTHLY__MONTHLY__CALENDAR_YEAR__WATER_YEAR = (
        "DAILY, HOURLY, SEMIMONTHLY, MONTHLY, CALENDAR_YEAR, WATER_YEAR"
    )


@dataclass
class StationElementDTO:
    elementCode: Optional[str] = None
    ordinal: Optional[int] = None
    heightDepth: Optional[int] = None
    durationName: Optional[DurationName] = None
    dataPrecision: Optional[int] = None
    storedUnitCode: Optional[str] = None
    originalUnitCode: Optional[str] = None
    beginDate: Optional[str] = None
    endDate: Optional[str] = None
    derivedData: Optional[bool] = None


@dataclass
class UnitDTO:
    code: Optional[str] = None
    singularName: Optional[str] = None
    pluralName: Optional[str] = None
    description: Optional[str] = None


@dataclass
class DataDTO:
    stationElement: Optional[StationElementDTO] = None
    values: Optional[List[DataValueDTO]] = None
    error: Optional[str] = None


@dataclass
class ForecastDTO:
    stationTriplet: Optional[str] = None
    forecastPointName: Optional[str] = None
    data: Optional[List[ForecastDataDTO]] = None


@dataclass
class ReferenceDataDTO:
    dcos: Optional[List[DcoDTO]] = None
    durations: Optional[List[DurationDTO]] = None
    elements: Optional[List[ElementDTO]] = None
    forecastPeriods: Optional[List[ForecastPeriodDTO]] = None
    functions: Optional[List[FunctionDTO]] = None
    instruments: Optional[List[InstrumentDTO]] = None
    networks: Optional[List[NetworkDTO]] = None
    physicalElements: Optional[List[PhysicalElementDTO]] = None
    states: Optional[List[StateDTO]] = None
    units: Optional[List[UnitDTO]] = None


@dataclass
class StationDTO:
    stationId: str
    stationTriplet: Optional[str] = None
    stateCode: Optional[str] = None
    networkCode: Optional[str] = None
    name: Optional[str] = None
    dcoCode: Optional[str] = None
    countyName: Optional[str] = None
    huc: Optional[str] = None
    elevation: Optional[float] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    dataTimeZone: Optional[float] = None
    pedonCode: Optional[str] = None
    shefId: Optional[str] = None
    operator: Optional[str] = None
    beginDate: Optional[str] = None
    endDate: Optional[str] = None
    forecastPoint: Optional[ForecastPointDTO] = None
    reservoirMetadata: Optional[ReservoirMetadataDTO] = None
    stationElements: Optional[List[StationElementDTO]] = None


@dataclass
class StationDataDTO:
    stationTriplet: Optional[str] = None
    data: Optional[List[DataDTO]] = None
