# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

# generated by datamodel-codegen:
#   filename:  https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
#   timestamp: 2025-03-19T18:26:23+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class DataValueDTO(BaseModel):
    date: str | None = Field(
        None,
        description="The timestamp of the data. Used only for DAILY and HOURLY durations.",
        examples=["2022-01-01"],
    )
    month: int | None = Field(
        None,
        description="The month of the data value (1-12). Used only for MONTHLY and SEMIMONTHLY durations.",
        examples=[1],
    )
    monthPart: str | None = Field(
        None,
        description="The half of month of the data value ('1' for first half, '2' for second half). Used only for SEMIMONTHLY durations.",
        examples=["1"],
    )
    year: int | None = Field(
        None,
        description="The year of the data value. Used only for WATER_YEAR, CALENDAR_YEAR, MONTHLY, and SEMIMONTHLY durations.",
        examples=[2022],
    )
    collectionDate: str | None = Field(
        None,
        description="The date the data value was collected. Used only for SEMIMONTHLY durations.",
        examples=["2021-12-31"],
    )
    value: float | None = Field(None, description="The data value", examples=[1.2])
    qcFlag: str | None = Field(
        None, description="The qc flag of the data value", examples=["E"]
    )
    qaFlag: str | None = Field(
        None, description="The qa flag of the data value", examples=["A"]
    )
    origValue: float | None = Field(
        None, description="The original data value", examples=[1.3]
    )
    origQcFlag: str | None = Field(
        None, description="The original qc flag of the data value", examples=["V"]
    )
    average: float | None = Field(
        None, description="The 30-year average", examples=[1.4]
    )
    median: float | None = Field(None, description="The 30-year median", examples=[1.0])


class DcoDTO(BaseModel):
    code: str | None = Field(None, description="The DCO code", examples=["OR"])
    name: str | None = Field(None, description="The DCO Name", examples=["OREGON"])


class DurationDTO(BaseModel):
    code: str | None = Field(None, description="The duration code", examples=["D"])
    name: str | None = Field(None, description="The duration name", examples=["DAILY"])
    durationMinutes: str | None = Field(
        None, description="The duration in minutes", examples=["1440"]
    )


class ElementDTO(BaseModel):
    code: str | None = Field(None, description="The element code", examples=["PREC"])
    name: str | None = Field(
        None, description="The element name", examples=["PRECIPITATION ACCUMULATION"]
    )
    physicalElementName: str | None = Field(
        None,
        description="The physical element name",
        examples=["precipitation accumulation"],
    )
    functionCode: str | None = Field(
        None, description="The function code", examples=["C"]
    )
    dataPrecision: int | None = Field(
        None, description="The precision of the data", examples=[2]
    )
    description: str | None = Field(
        None,
        description="The element description",
        examples=["Water Year Accumulated Precipitation"],
    )
    storedUnitCode: str | None = Field(
        None, description="The stored unit code", examples=["in"]
    )
    englishUnitCode: str | None = Field(
        None, description="The english unit code", examples=["in"]
    )
    metricUnitCode: str | None = Field(
        None, description="The metric unit code", examples=["mm"]
    )


class ForecastDataDTO(BaseModel):
    elementCode: str | None = Field(
        None,
        description="The element code related to the forecast record.",
        examples=["SRVO"],
    )
    forecastPeriod: list[str] | None = Field(
        None,
        description="The start (MM-DD) and end (MM-DD) of the forecast period that the forecast is for.",
        examples=[["04-01", "07-31"]],
    )
    forecastStatus: str | None = Field(
        None, description="Indicates the status of the Forecast.", examples=["final"]
    )
    issueDate: str | None = Field(
        None,
        description="The issue date of the forecast.",
        examples=["2023-10-02 07:45:52"],
    )
    periodNormal: float | None = Field(
        None, description="The forecast period normal.", examples=[13.6]
    )
    publicationDate: str | None = Field(
        None,
        description="The publication date of the forecast value.",
        examples=["2023-04-01"],
    )
    unitCode: str | None = Field(
        None, description="The unit code of a forecast.", examples=["kac_ft"]
    )
    forecastValues: dict[str, float] | None = Field(
        None,
        description="A dictionary of forecast values where the key is the exceedence probability and the value is the corresponding forecast value.",
        examples=[{"10": 36.5, "30": 28.3, "50": 24.1}],
    )


class ForecastPeriodDTO(BaseModel):
    code: str | None = Field(
        None, description="The forecast period code", examples=["D1"]
    )
    name: str | None = Field(
        None, description="The forecast period name", examples=["J15-JAN"]
    )
    description: str | None = Field(
        None,
        description="The forecast period description",
        examples=["Jan 15 through Jan"],
    )
    beginMonthDay: str | None = Field(
        None,
        description="The beginning month and day for the forecast period",
        examples=["01-15"],
    )
    endMonthDay: str | None = Field(
        None,
        description="The ending month and day for the forecast period",
        examples=["01-31"],
    )


class ForecastPointDTO(BaseModel):
    name: str | None = Field(
        None,
        description="The name of the forecast point",
        examples=["Alamosa Ck ab Terrace Reservoir"],
    )
    forecaster: str | None = Field(
        None,
        description="The user name of the forecaster who forecasts for this station",
        examples=["agoodbody"],
    )
    exceedenceProbabilities: list[int] | None = Field(
        None,
        description="The name to display in the UI for the profile type",
        examples=[[10, 30, 50, 70, 90]],
    )


class FunctionDTO(BaseModel):
    code: str | None = Field(None, description="The function code", examples=["C"])
    abbreviation: str | None = Field(
        None, description="The abbreviation", examples=["OBS"]
    )
    name: str | None = Field(
        None, description="The name", examples=["current observation"]
    )


class InstrumentDTO(BaseModel):
    name: str | None = Field(
        None, description="The instrument name", examples=['150" transducer - unknown']
    )
    transducerLength: int | None = Field(
        None, description="The transducer length", examples=[150]
    )
    dataPrecisionAdjustment: int | None = Field(
        None, description="The data precision adjustment", examples=[0]
    )
    manufacturer: str | None = Field(
        None, description="The manufacturer", examples=["Sensotec/Druck/Edcliff"]
    )
    model: str | None = Field(None, description="The model", examples=["unknown"])


class NetworkDTO(BaseModel):
    code: str | None = Field(None, description="The network code", examples=["USGS"])
    name: str | None = Field(
        None, description="The network name", examples=["STREAMFLOW"]
    )
    description: str | None = Field(
        None,
        description="The network description",
        examples=["STREAMFLOW NETWORK STATIONS"],
    )


class PhysicalElementDTO(BaseModel):
    name: str | None = Field(
        None, description="The physical element name", examples=["snow depth"]
    )
    shefPhysicalElementCode: str | None = Field(
        None, description="The SHEF physical element code", examples=["SD"]
    )


class ReservoirMetadataDTO(BaseModel):
    capacity: float | None = Field(
        None,
        description="The capacity of the reservoir in acre-feet",
        examples=[153000.0],
    )
    elevationAtCapacity: float | None = Field(
        None,
        description="The elevation of the reservoir (in feet) when it is at capacity",
        examples=[350.0],
    )
    usableCapacity: float | None = Field(
        None,
        description="The usable capacity of the reservoir in acre-feet",
        examples=[148640.0],
    )


class StateDTO(BaseModel):
    code: str | None = Field(None, description="The state code", examples=["CO"])
    fipsNumber: str | None = Field(
        None, description="The state FIPS number code", examples=["08"]
    )
    name: str | None = Field(None, description="The state name", examples=["COLORADO"])
    countryCode: str | None = Field(
        None, description="The country code", examples=["US"]
    )


class DurationName(str, Enum):
    DAILY = "DAILY"
    HOURLY = "HOURLY"
    SEMIMONTHLY = "SEMIMONTHLY"
    MONTHLY = "MONTHLY"
    CALENDAR_YEAR = "CALENDAR_YEAR"
    WATER_YEAR = "WATER_YEAR"
    INSTANTANEOUS = "INSTANTANEOUS"
    SEASONAL = "SEASONAL"
    DAILY__HOURLY__SEMIMONTHLY__MONTHLY__CALENDAR_YEAR__WATER_YEAR = (
        "DAILY, HOURLY, SEMIMONTHLY, MONTHLY, CALENDAR_YEAR, WATER_YEAR"
    )


class StationElementDTO(BaseModel):
    elementCode: str | None = Field(
        None, description="The element code", examples=["WTEQ"]
    )
    ordinal: int | None = Field(
        None, description="The ordinal of the station element", examples=[1]
    )
    heightDepth: int | None = Field(
        None, description="The height/depth of the station element in inches"
    )
    durationName: DurationName | None = Field(
        None, description="The duration name of the station element", examples=["DAILY"]
    )
    dataPrecision: int | None = Field(
        None,
        description="The data precision of the data for the station element",
        examples=[2],
    )
    storedUnitCode: str | None = Field(
        None, description="The units that the data is stored in", examples=["in"]
    )
    originalUnitCode: str | None = Field(
        None, description="The units that the data was collected in", examples=["in"]
    )
    beginDate: str | None = Field(
        None,
        description="The date that the station element was put into service",
        examples=["1980-10-30 15:53"],
    )
    endDate: str | None = Field(
        None,
        description="The date that the station element was taken out of service or 2100-01-01 if still in service",
        examples=["2100-01-01"],
    )
    derivedData: bool | None = Field(
        None,
        description="true/false if the station element data is derived",
        examples=[False],
    )


class UnitDTO(BaseModel):
    code: str | None = Field(None, description="The unit code", examples=["bar"])
    singularName: str | None = Field(
        None, description="The singular unit name", examples=["bar"]
    )
    pluralName: str | None = Field(
        None, description="The plural unit name", examples=["bars"]
    )
    description: str | None = Field(
        None, description="The unit description", examples=["barometric pressure"]
    )


class DataDTO(BaseModel):
    stationElement: StationElementDTO | None = None
    values: list[DataValueDTO] | None = None
    error: str | None = Field(
        None,
        examples=[
            "Unsupported operation - the insertOrUpdateBeginDate parameter is not supported for derived data (NOTE: Only included when there is an error)."
        ],
    )


class ForecastDTO(BaseModel):
    stationTriplet: str | None = Field(
        None,
        description="The station triplet of the forecast point.",
        examples=["09430500:CO:USGS"],
    )
    forecastPointName: str | None = Field(
        None, description="The name of the forecast point.", examples=["Gila R at Gila"]
    )
    data: list[ForecastDataDTO] | None = Field(
        None, description="Contains forecast data for a forecast point."
    )


class ReferenceDataDTO(BaseModel):
    dcos: list[DcoDTO] | None = Field(None, description="Contains DCO reference data.")
    durations: list[DurationDTO] | None = Field(
        None, description="Contains duration reference data."
    )
    elements: list[ElementDTO] | None = Field(
        None, description="Contains element reference data."
    )
    forecastPeriods: list[ForecastPeriodDTO] | None = Field(
        None, description="Contains forecast period reference data."
    )
    functions: list[FunctionDTO] | None = Field(
        None, description="Contains function reference data."
    )
    instruments: list[InstrumentDTO] | None = Field(
        None, description="Contains instrument reference data."
    )
    networks: list[NetworkDTO] | None = Field(
        None, description="Contains network reference data."
    )
    physicalElements: list[PhysicalElementDTO] | None = Field(
        None, description="Contains physical element reference data."
    )
    states: list[StateDTO] | None = Field(
        None, description="Contains State reference data."
    )
    units: list[UnitDTO] | None = Field(
        None, description="Contains unit reference data."
    )


class StationDTO(BaseModel):
    stationTriplet: str | None = Field(
        None, description="The station triplet of the station", examples=["302:OR:SNTL"]
    )
    stationId: str = Field(..., description="The id of the station", examples=["302"])
    stateCode: str | None = Field(
        None, description="The 2-character state code of the station", examples=["OR"]
    )
    networkCode: str | None = Field(
        None, description="The network code of the station", examples=["SNTL"]
    )
    name: str | None = Field(
        None, description="The name of the station", examples=["ANEROID LAKE #2"]
    )
    dcoCode: str | None = Field(
        None, description="The DCO code of the station", examples=["OR"]
    )
    countyName: str | None = Field(
        None,
        description="The name of the county that the station is located in",
        examples=["Wallowa"],
    )
    huc: str | None = Field(
        None,
        description="The hydrologic unit code of the station",
        examples=["170601050101"],
    )
    elevation: float | None = Field(
        None, description="The elevation (in feet) of the station", examples=[7400.0]
    )
    latitude: float | None = Field(
        None, description="The latitude of the station", examples=[45.21328]
    )
    longitude: float | None = Field(
        None, description="The longitude of the station", examples=[45.21328]
    )
    dataTimeZone: float | None = Field(
        None,
        description="The timezone offset from GMT of the data for the station",
        examples=[-8.0],
    )
    pedonCode: str | None = Field(
        None, description="The NRCS pedon code for the station"
    )
    shefId: str | None = Field(
        None, description="The SHEF id of the station", examples=["ANR03"]
    )
    beginDate: str | None = Field(
        None,
        description="The date that the station was put into service",
        examples=["1980-10-01 00:00"],
    )
    endDate: str | None = Field(
        None,
        description="The date that the station was taken out of service or 2100-01-01 if still in service",
        examples=["2100-01-01"],
    )
    forecastPoint: ForecastPointDTO | None = None
    reservoirMetadata: ReservoirMetadataDTO | None = None
    stationElements: list[StationElementDTO] | None = Field(
        None, description="The station elements of the station"
    )


class StationDataDTO(BaseModel):
    stationTriplet: str | None = Field(
        None, description="The station triplet of the station", examples=["302:OR:SNTL"]
    )
    data: list[DataDTO] | None = None
