server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5005
  url: ${PYGEOAPI_URL:-http://localhost:5005} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  templates:
    path: /opt/pygeoapi/pygeoapi-deployment/templates
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOGLEVEL:-ERROR}
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: Western Water Datahub
    description: The Western Water Datahub is an implementation of OGC API - EDR supported by the United States Bureau of Reclamation.
    keywords:
      - usbr
      - wwdh
      - iow
    keywords_type: theme
    terms_of_service: https://opensource.org/license/MIT
    url: https://github.com/internetofwater/WWDH
  license:
    name: MIT License
    url: https://opensource.org/license/MIT
  provider:
    name: Internet of Water
    url: https://github.com/internetofwater/WWDH
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://cgsearth.org
    role: pointOfContact
    name: Benjamin Webb

resources:
  rise-edr:
    type: collection
    title: Reclamation Information Sharing Environment (RISE)
    description: United States Bureau of Reclamation Information Sharing Environment EDR
    keywords:
      - EDR
      - RISE
      - USBR
    links:
      - &default-link
        type: application/html
        rel: canonical
        title: data source
        href: https://data.usbr.gov/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-123.60518, 28.4667, -95.875, 48.8283]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - &default-edr
        type: edr
        name: rise.rise_edr.RiseEDRProvider
        data: https://data.usbr.gov/
        title_field: name
      - &default-feature
        type: feature
        name: rise.rise.RiseProvider
        data: https://data.usbr.gov/
        title_field: name

  snotel-edr:
    type: collection
    title: Snow Telemetry Network (SNOTEL)
    description: United States Department of Agriculture Snow Telemetry Network EDR
    keywords:
      - EDR
      - SNOTEL
      - NRCS
      - USDA
    links:
      - <<: *default-link
        href: https://www.nrcs.usda.gov/wps/portal/wcc/home/aboutUs/monitoringPrograms/automatedSnowMonitoring/
    extents:
      spatial:
        bbox: [-164.92472, 32.92342, -103.78758, 70.28062]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - <<: *default-edr
        name: snotel.snotel_edr.SnotelEDRProvider
        data: https://wcc.sc.egov.usda.gov/
      - <<: *default-feature
        name: snotel.snotel.SnotelProvider
        data: https://wcc.sc.egov.usda.gov/

  usgs-sta:
    type: collection
    title: United States Geologic Survey SensorThings API
    description: United States Geologic Survey SensorThings API EDR
    keywords:
      - EDR
      - SensorThings
      - USGS
    links:
      - <<: *default-link
        href: https://labs.waterdata.usgs.gov
    extents: &default-extent
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: SensorThingsEDR
        data: https://labs.waterdata.usgs.gov/sta/v1.1/
      - type: feature
        name: SensorThings
        data: https://labs.waterdata.usgs.gov/sta/v1.1/
        entity: Things
        title_field: name

  awdb-forecasts-edr:
    type: collection
    title: Air and Water Database (AWDB) Forecasts
    description: United States Department of Agriculture Air and Water Database Forecasts EDR
    keywords:
      - open data
    extents: *default-extent
    providers:
      - type: edr
        name: awdb_forecasts.awdb_forecasts_edr.AwdbForecastsEDRProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
      - type: feature
        name: awdb_forecasts.awdb_forecasts.AwdbForecastsProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
        title_field: name

  usace-edr:
    type: collection
    title: US Army Corps of Engineers (USACE) EDR
    description: US Army Corps of Engineers EDR
    keywords:
      - open data
    extents: *default-extent
    providers:
      - type: edr
        name: usace.usace_edr.USACEEDRProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
      - type: feature
        name: usace.usace.USACEProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
        entity: Observation
        title_field: name

  noaa-qpf-24-hour-day-1: &default-qpf
    type: collection
    title: NOAA QPF 24 Hours Day 1
    description: NOAA Quantitative Precipitation Forecast (QPF) 24 Hours Day 1
    keywords: [NOAA, QPF]
    links:
      - <<: *default-link
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer
    extents: *default-extent
    providers:
      - &default-feature-qpf
        type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/1
        id_field: objectid
        time_field: issue_time

  noaa-qpf-24-hour-day-2:
    <<: *default-qpf
    title: NOAA QPF 24 Hours Day 2
    description: NOAA Quantitative Precipitation Forecast (QPF) 24 Hours Day 2
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/2

  noaa-qpf-24-hour-day-3:
    <<: *default-qpf
    title: NOAA QPF 24 Hours Day 3
    description: NOAA Quantitative Precipitation Forecast (QPF) 24 Hours Day 3
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/3

  noaa-qpf-48-hour-day-4:
    <<: *default-qpf
    title: NOAA QPF 48 Hours Day 4-5
    description: NOAA Quantitative Precipitation Forecast (QPF) 48 Hours Day 4-5
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/4

  noaa-qpf-48-hour-day-6-7:
    <<: *default-qpf
    title: NOAA QPF 48 Hour Day 6-7
    description: NOAA Quantitative Precipitation Forecast (QPF) 48 Hour Day 6-7
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/5

  noaa-qpf-cumulative-6-hours-day-1:
    <<: *default-qpf
    title: NOAA QPF Cumulative 6 Hours Day 1
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 6 Hours Day 1
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/7

  noaa-qpf-cumulative-48-hours-day-1-2:
    <<: *default-qpf
    title: NOAA QPF Cumulative 48 Hours Day 1-2
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 48 Hours Day 1-2
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/8

  noaa-qpf-cumulative-72-hours-day-1-3:
    <<: *default-qpf
    title: NOAA QPF Cumulative 72 Hours Day 1-3
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 72 Hours Day 1-3
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/9

  noaa-qpf-cumulative-120-hours-day-1-5:
    <<: *default-qpf
    title: NOAA QPF Cumulative 120 Hours Day 1-5
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 120 Hours Day 1-5
    providers:
      - <<: *default-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/10

  noaa-qpf-cumulative-168-hours-day-1-7:
    <<: *default-qpf
    title: NOAA QPF Cumulative 168 Hours Day 1-7
    description: NOAA Quantitative Precipitation Forecast (QPF) Cumulative 168 Hours Day 1-7
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_qpf/MapServer/11

  noaa-day-1-prob-at-least-4-inches-snow: &default-wpc
    <<: *default-qpf
    title: NOAA Day 1 Prob At Least 4 Inches Snow
    description: NOAA Day 1 Prob At Least 4 Inches Snow
    links:
      - <<: *default-link
        href: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/1

  noaa-day-1-prob-at-least-8-inches-snow:
    <<: *default-qpf
    title: NOAA Day 1 Prob At Least 8 Inches Snow
    description: NOAA Day 1 Prob At Least 8 Inches Snow
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/2

  noaa-day-1-prob-at-least-12-inches-snow:
    <<: *default-wpc
    title: NOAA Day 1 Prob At Least 12 Inches Snow
    description: NOAA Day 1 Prob At Least 12 Inches Snow
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/3

  noaa-day-1-prob-icing-at-least-.25-inches:
    <<: *default-wpc
    title: NOAA Day 1 Prob Icing At Least .25 Inches
    description: NOAA Day 1 Prob Icing At Least .25 Inches
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/vector/rest/services/precip/wpc_prob_winter_precip/MapServer/4

  nohrsc-swe:
    type: collection
    title: NOAA NOHRSC Snow Water Forecast
    description: NOAA NOHRSC Snow Water Forecast
    keywords:
      - nohrsc
      - snow water equivalent
    links:
      - <<: *default-link
        title: information
        href: https://www.nohrsc.noaa.gov/nsa/
    extents:
      spatial:
        bbox: [-130.516667, 24.1, -62.25273100000001, 58.240301]
        crs: http://www.opengis.net/def/crs/EPSG/0/4269
    providers:
      - &default-wms
        type: map
        name: WMSFacade
        data: https://mapservices.weather.noaa.gov/raster/services/snow/NOHRSC_Snow_Analysis/MapServer/WMSServer
        options:
          layer: 1
          style: default
          projection: 4269
        format:
          name: png
          mimetype: image/png

  nohrsc-sd:
    type: collection
    title: NOAA NOHRSC Snow Depth Forecast
    description: NOAA NOHRSC Snow Depth Forecast
    keywords:
      - nohrsc
      - snow depth
    links:
      - <<: *default-link
        title: information
        href: https://www.nohrsc.noaa.gov/nsa/
    extents: *default-extent
    providers:
      - <<: *default-wms
        data: https://mapservices.weather.noaa.gov/raster/services/snow/NOHRSC_Snow_Analysis/MapServer/WMSServer

  NOHRSC-Snow-Analysis-Snow-Water-Boundary:
    <<: *default-wpc
    title: NOAA NOHRSC Snow Analysis Snow Water Boundary
    description: NOAA NOHRSC Snow Analysis Snow Water Boundary
    providers:
      - <<: *default-feature-qpf
        data: https://mapservices.weather.noaa.gov/raster/rest/services/snow/NOHRSC_Snow_Analysis/MapServer/5

  noaa-rfc:
    type: collection
    title: NOAA RFC Forecasts
    description: NOAA River Forecast Center Forecasts
    keywords: [NOAA]
    links:
      - <<: *default-link
        href: https://www.cbrfc.noaa.gov/wsup/graph/west/map/esp_map.html
    extents: *default-extent
    providers:
      - type: feature
        name: noaa_rfc.noaa_rfc.NOAARFCProvider
        data: https://www.cbrfc.noaa.gov/wsup/graph/west/map/esp_map.html
        title_field: espname

  noaa-6-10-day-temp:
    type: collection
    title: NOAA 6-10 Day Temperature Forecast
    description: NOAA 6-10 Day Temperature Forecast
    keywords: [NOAA, temperature]
    links:
      - <<: *default-link
        href: https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/cpc_6_10_day_outlk/MapServer/0r
    extents: *default-extent
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/cpc_6_10_day_outlk/MapServer/0
        id_field: objectid
        time_field: fcst_date

  noaa-6-10-day-precip:
    type: collection
    title: NOAA 6-10 Day Precipitation Forecast
    description: NOAA 6-10 Day Precipitation Forecast
    keywords: [NOAA, temperature]
    links:
      - <<: *default-link
        href: https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/cpc_6_10_day_outlk/MapServer/1
    extents: *default-extent
    providers:
      - type: feature
        name: ESRI
        data: https://mapservices.weather.noaa.gov/vector/rest/services/outlooks/cpc_6_10_day_outlk/MapServer/1
        id_field: objectid
        time_field: fcst_date

  us-drought-monitor:
    type: collection
    title: US Drought Monitor 
    description: US Drought Monitor current drought intensity
    keywords: ["drought"]
    links:
      - <<: *default-link
        href: https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/US_Drought_Intensity_v1/FeatureServer/3
    extents: *default-extent
    providers:
      - type: feature
        name: ESRI
        data:  https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/US_Drought_Intensity_v1/FeatureServer/3
        id_field: OBJECTID
        time_field: ddate

  usgs-prism:
    type: collection
    title: Parameter-elevation Regressions on Independent Slopes Model (PRISM)
    description: PRISM Monthly Climate Data for the Continental United States
    keywords:
      - temperature
      - precipitation
    extents: *default-extent
    links:
      - <<: *default-link
        title: information
        href: https://cida.usgs.gov/thredds/catalog.html?dataset=cida.usgs.gov/prism_v2
    providers:
      - type: edr
        name: xarray-edr
        data: s3://mdmf/gdp/PRISM_v2.zarr
        format:
          name: zarr
          mimetype: application/zip
        options:
          s3:
            anon: true
            requester_pays: false
            client_kwargs:
              endpoint_url: https://usgs.osn.mghpcc.org/

  resviz-edr:
    type: collection
    title: Columbia Pacific Northwest Region
    description: Columbia Pacific Northwest Region
    keywords:
      - temperature
      - precipitation
    extents:
      spatial:
        bbox: [-124.76, 41.13, -109.74, 48.99]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    links:
      - <<: *default-link
        title: information
        href: https://cida.usgs.gov/thredds/catalog.html?dataset=cida.usgs.gov/prism_v2
    providers:
      - type: feature
        name: PostgreSQL
        data: &postgres-data
          host: ${POSTGRES_HOST:-localhost}
          dbname: ${POSTGRES_DB:-edr}
          user: ${POSTGRES_USER:-postgres}
          password: ${POSTGRES_PASSWORD:-password}
        table: resviz
        id_field: ogc_fid
        title_field: site_name
        geom_field: geom
      - type: edr
        name: pg_edr.edr.PostgresEDRProvider
        data: *postgres-data
        table: resviz

        edr_fields: # Required EDR Fields
          id_field: ogc_fid # Result identifier field
          geom_field: geom # Result identifier field
          time_field: data_date # Result time field


  # noaa-nwm:
  #   type: collection
  #   title: NOAA National Water Model CONUS Retrospective Dataset
  #   description: NOAA National Water Model CONUS Retrospective Dataset
  #   keywords:
  #     - national water model
  #     - agriculture
  #   extents:
  #     spatial:
  #       bbox: [-125.020836, 24.104166, -66.520836, 49.9375]
  #       crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
  #   links:
  #     - <<: *default-link
  #       href: https://registry.opendata.aws/nwm-archive/
  #   providers:
  #     - type: edr
  #       name: xarray-edr
  #       data: s3://noaa-nwm-retrospective-3-0-pds/CONUS/zarr/chrtout.zarr
  #       x_field: longitude
  #       y_field: latitude
  #       format:
  #         name: zarr
  #         mimetype: application/zip
  #       options:
  #         s3:
  #           anon: true
