# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

name: Pyright Type Checks

on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GDAL with Python bindings
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: gdal-bin libgdal-dev
          version: 3.6.4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev --all-packages --all-groups

      - name: Run type checks
        run: uv run pyright
